#!/bin/bash

while read file
do
    case "$1" in
        "w")
            prompt "Set $file as Wallpaper?" && setbg "$file" & ;;
        "d")
            prompt "Delete $file?" && rm "$file" ;;
        "D")
            rm "$file" ;;
        "m")
            mv "$file" "$(prompt_open 'New name' "$file")"
   esac
done
