#!/bin/bash

while read file
do
    case "$1" in
        "w")
            prompt "Set $(basename -- $file) as Wallpaper?" && setbg "$file" & ;;
        "d")
            prompt "Delete $(basename -- $file)?" && rm "$file" ;;
        "D")
            rm "$file" ;;
        "m")
            mv "$file" "$(prompt_open 'New name' "$file")"
   esac
done
